# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "ubuntu1404" do |vm1|
      vm1.vm.box = "ubuntu/trusty64"
      vm1.vm.box_version = "20190429.0.1"
      vm1.vm.hostname = "ubuntu1404"
      vm1.vm.provider :virtualbox do |vb|
        vb.memory = 114688
        vb.cpus = "32"
#       vb.disksize.size = "100GB"
      end
      vm1.vm.synced_folder "/data/aming/vagrant/bench", "/home/vagrant/bench"
      # config.ssh.insert_key = false
      # config.ssh.forward_env = ["CUSTOM_VAR"]
      vm1.vm.provision "shell", inline: <<-SHELL
        # dpkg --add-architecture i386
        # apt-get update -y
        # apt-get install -y any-packages-you-need
        echo 'export VISUAL=vim' >> /home/vagrant/.bashrc
        echo 'set -o vi' >> /home/vagrant/.bashrc
        export DEBIAN_FRONTEND=noninteractive
        apt-get -y update
        # apt-get -y dist-upgrade
        # zsim dependencies
        apt-get -y install build-essential g++ git scons
        apt-get -y install libelfg0-dev libhdf5-serial-dev libconfig++-dev
        # dependencies for zsim's Fortran and Java hooks (misc/hooks)
        apt-get -y install gfortran openjdk-7-jdk
        # other packages
        apt-get -y install vim
        # Download the Pin & set PINPATH
        #PINVER="pin-2.12-58423-gcc.4.4.7-linux"
        PINVER="pin-2.14-67254-gcc.4.4.7-linux" # PINVER="pin-2.13-62732-gcc.4.4.7-linux"
        if [ ! -d ~vagrant/${PINVER} ]; then
            echo "Downloading Pin version ${PINVER}"
            #sudo -u vagrant wget -nc -nv http://software.intel.com/sites/landingpage/pintool/downloads/${PINVER}.tar.gz
            #sudo -u vagrant tar xzf ${PINVER}.tar.gz
            echo "export PINPATH=~/bench/${PINVER}" >> ~vagrant/.bashrc
        fi
        # Configure system flags
        sysctl -w kernel.shmmax=34359738368 #=32GB   #1073741824 #=1GB - 4GB max for 32-bit OS
        sysctl -w kernel.shmall=34359738368 #=32GB
        sysctl -w kernel.yama.ptrace_scope=0
      SHELL
    end
end
